create table public.titanic (
  id bigint generated by default as identity not null,
  orig_id smallint null,
  customer_id TEXT,
  first_name TEXT,
  last_name TEXT,
  company TEXT,
  city TEXT,
  country TEXT,
  phone_1 TEXT,
  phone_2 TEXT,
  email TEXT,
  subscription_date DATE,
  website TEXT,
  constraint titanic_pkey primary key (id)
) TABLESPACE pg_default;